version: '2.1'


services:
  mongodb:
    image: mongo
  knote:
    image: knote-java
    ports:
      - "8080:8080"
    environment:
      MONGO_URL: mongodb://mongodb:27017/test
    depends_on:
      - mongodb
